language: android
sudo: true

install:
- echo y | android update sdk -u -a -t tools
- echo y | android update sdk -u -a -t platform-tools
- echo y | android update sdk -u -a -t build-tools-26.0.2
- echo y | android update sdk -u -a -t android-25
- echo y | android update sdk -u -a -t extra-google-m2repository
- echo y | android update sdk -u -a -t extra-android-m2repository

script: ./gradlew assembleRelease testReleaseUnitTest lintRelease

after_failure:
- cat app/build/reports/tests/debug/index.html
